name: langchain
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - altair=5.5.0
  - aom=3.6.0
  - arrow-cpp=19.0.0
  - attrs=24.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.3
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.2
  - aws-c-io=0.20.1
  - aws-c-mqtt=0.13.2
  - aws-c-s3=0.8.3
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.32.10
  - aws-sdk-cpp=1.11.528
  - blas=1.0
  - blinker=1.9.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - click=8.2.1
  - dav1d=1.2.1
  - expat=2.7.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gflags=2.2.2
  - gitdb=4.0.12
  - gitpython=3.1.43
  - glog=0.5.0
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.1.1
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcurl=8.14.1
  - libdeflate=1.22
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libpng=1.6.39
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - narwhals=1.31.0
  - ncurses=6.5
  - numexpr=2.11.0
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - orc=2.1.1
  - packaging=25.0
  - pandas=2.3.1
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.46.4
  - pthread-stubs=0.3
  - pyarrow=19.0.0
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pysocks=1.7.1
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - pyyaml=6.0.2
  - re2=2024.07.02
  - readline=8.3
  - referencing=0.30.2
  - rpds-py=0.22.3
  - s2n=1.5.14
  - setuptools=78.1.1
  - six=1.17.0
  - smmap=5.0.2
  - snappy=1.2.1
  - sqlite=3.50.2
  - streamlit=1.48.0
  - tbb=2021.8.0
  - tk=8.6.15
  - toml=0.10.2
  - tornado=6.5.1
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - watchdog=4.0.2
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.64.0
      - anyio==4.10.0
      - cachetools==5.5.2
      - chardet==5.2.0
      - charset-normalizer==3.4.3
      - distro==1.9.0
      - dnspython==2.7.0
      - email-validator==2.2.0
      - filelock==3.19.1
      - filetype==1.2.0
      - fsspec==2025.7.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.179.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.4
      - grpcio==1.74.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.1.8
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.27
      - langchain-anthropic==0.3.19
      - langchain-core==0.3.74
      - langchain-google-genai==2.0.10
      - langchain-huggingface==0.3.1
      - langchain-openai==0.3.30
      - langchain-text-splitters==0.3.9
      - langsmith==0.4.15
      - numpy==2.3.2
      - openai==1.100.2
      - orjson==3.11.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.3
      - python-dotenv==1.1.1
      - regex==2025.7.34
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - tokenizers==0.21.4
      - tqdm==4.67.1
      - transformers==4.55.2
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - uritemplate==4.2.0
      - zstandard==0.24.0
