name: langchain
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.7.15
  - expat=2.7.1
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - ncurses=6.5
  - openssl=3.0.17
  - pip=25.1
  - pthread-stubs=0.3
  - python=3.11.13
  - readline=8.3
  - setuptools=78.1.1
  - sqlite=3.50.2
  - tk=8.6.15
  - tzdata=2025b
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - annotated-types==0.7.0
      - anthropic==0.64.0
      - anyio==4.10.0
      - cachetools==5.5.2
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - distro==1.9.0
      - filelock==3.19.1
      - filetype==1.2.0
      - fsspec==2025.7.0
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.25.1
      - google-api-python-client==2.179.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.70.0
      - greenlet==3.2.4
      - grpcio==1.74.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - hf-xet==1.1.8
      - httpcore==1.0.9
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.34.4
      - idna==3.10
      - jiter==0.10.0
      - joblib==1.5.1
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - langchain==0.3.27
      - langchain-anthropic==0.3.19
      - langchain-core==0.3.74
      - langchain-google-genai==2.0.10
      - langchain-huggingface==0.3.1
      - langchain-openai==0.3.30
      - langchain-text-splitters==0.3.9
      - langsmith==0.4.15
      - numpy==2.3.2
      - openai==1.100.2
      - orjson==3.11.2
      - packaging==25.0
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyparsing==3.2.3
      - python-dotenv==1.1.1
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.43
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tiktoken==0.11.0
      - tokenizers==0.21.4
      - tqdm==4.67.1
      - transformers==4.55.2
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - zstandard==0.24.0
